### ISSUE TITLE
Issue-update readme

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/one-listen#14]
Automated Review Comments
Issues in .vscode/settings.json:
  - (4, 'Hardcoded string found')
Issues in README.md:
  - (2, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
  - (23, 'Line exceeds 80 characters')
  - (25, 'Line exceeds 80 characters')
  - (31, 'Line exceeds 80 characters')
  - (33, 'Line exceeds 80 characters')
  - (37, 'Line exceeds 80 characters')
  - (38, 'Line exceeds 80 characters')
  - (42, 'Line exceeds 80 characters')
  - (48, 'Line exceeds 80 characters')
  - (53, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
