### ISSUE TITLE
Issue-use the nuxt frontend

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/one-listen#18]
Automated Review Comments
Issues in .gitignore:
  - (2, 'Line exceeds 80 characters')
Issues in .vscode/extensions.json:
  - (3, 'Hardcoded string found')
Issues in README.md:
  - (6, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (86, 'Line exceeds 80 characters')
  - (89, 'Line exceeds 80 characters')
Issues in nuxt.config.ts:
  - (7, 'Line exceeds 80 characters')
  - (21, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (22, 'Hardcoded string found')
  - (25, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
  - (31, 'Hardcoded string found')
  - (32, 'Hardcoded string found')
  - (33, 'Hardcoded string found')
Issues in server/tsconfig.json:
  - (3, 'Hardcoded string found')
Issues in src-tauri/Cargo.toml:
  - (3, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (32, 'Line exceeds 80 characters')
  - (32, 'Hardcoded string found')
Issues in src-tauri/capabilities/default.json:
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
