### ISSUE TITLE
Issue-title bar

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/one-listen#26]
Automated Review Comments
Issues in app.config.ts:
  - (3, 'Hardcoded string found')
Issues in components/TitleBar.vue:
  - (2, 'Hardcoded string found')
  - (22, 'Line exceeds 80 characters')
  - (26, 'Hardcoded string found')
  - (27, 'Line exceeds 80 characters')
  - (30, 'Hardcoded string found')
  - (31, 'Line exceeds 80 characters')
  - (34, 'Line exceeds 80 characters')
  - (34, 'Hardcoded string found')
Issues in layouts/default.vue:
  - (2, 'Hardcoded string found')
Issues in src-tauri/Cargo.toml:
  - (4, 'Hardcoded string found')
  - (9, 'Line exceeds 80 characters')
Issues in src-tauri/tauri.conf.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (20, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
