### ISSUE TITLE
Issue-reflector the function from view by the composable

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/one-listen#28]
Automated Review Comments
Issues in composables/Greet.ts:
  - (2, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
Issues in pages/index.vue:
  - (2, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (15, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
