### ISSUE TITLE
Issue-+ release action

open rust Cache

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/one-listen#6]
Automated Review Comments
Issues in .github/workflows/release.yml:
  - (2, 'Hardcoded string found')
  - (10, 'Line exceeds 80 characters')
  - (35, 'Line exceeds 80 characters')
  - (36, 'Line exceeds 80 characters')
  - (50, 'Line exceeds 80 characters')
  - (56, 'Line exceeds 80 characters')

**Comment by satokihanada** [comment]
I got it.
