### ISSUE TITLE
Issue-action test

### ISSUE THREAD

**Issue by kazupot7** [kazupot7/one-listen#8]
Automated Review Comments
Issues in src-tauri/tauri.conf.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')

**Comment by satokihanada** [comment]
I got it.
